# YOLOv8-OBB dataset config for Fold 1
train: c:/Users/17638/Desktop/NUDT/智能图像处理/multimodal_detection/data_splits/train_fold1.txt
val: c:/Users/17638/Desktop/NUDT/智能图像处理/multimodal_detection/data_splits/val_fold1.txt

nc: 11
names:
  0: car
  1: suv
  2: van
  3: bus
  4: freight_car
  5: truck
  6: motorcycle
  7: trailer
  8: excavator
  9: crane
  10: tank_truck
